# Generated by Django 4.2.5 on 2023-10-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='postagens.postagem'),
            preserve_default=False,
        ),
    ]
