# Generated by Django 4.2.5 on 2023-10-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0004_comentario_corpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
